# Generated by Django 3.0 on 2020-03-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='organization',
            field=models.TextField(default='N/A', max_length=155),
        ),
    ]
