# Generated by Django 3.0 on 2020-03-05 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200305_1332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'managed': False},
        ),
    ]
