# Generated by Django 3.0 on 2020-03-05 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200305_1355'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='users_profile',
        ),
    ]
