# Generated by Django 3.0 on 2020-03-06 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200305_1410'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='users_profile ',
        ),
    ]
