# Generated by Django 3.0 on 2020-03-05 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isicwebdatabase', '0003_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_django'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='interoperability',
            table='interoperability',
        ),
    ]
