# Generated by Django 3.0 on 2020-03-06 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isicwebdatabase', '0004_auto_20200305_1410'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='interoperability',
            table='interoperability ',
        ),
    ]
