# Generated by Django 3.0 on 2020-03-09 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isicwebdatabase', '0006_isicapplicants'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='interoperability',
            table='interoperability',
        ),
        migrations.AlterModelTable(
            name='isicapplicants',
            table='applicants',
        ),
    ]
