# Generated by Django 3.0 on 2020-03-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isicwebdatabase', '0007_auto_20200309_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsicApplicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=255)),
                ('applicant_loi', models.BooleanField(default=False)),
                ('applicant_moa', models.BooleanField(default=False)),
                ('applicant_part_pl', models.BooleanField(default=False)),
                ('applicant_ugc', models.BooleanField(default=False)),
                ('applicant_isisb', models.BooleanField(default=False)),
                ('applicant_user_level', models.SmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'applicants ',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='IsicApplicants',
        ),
        migrations.AlterModelTable(
            name='interoperability',
            table='interoperability ',
        ),
    ]
