# Generated by Django 3.0 on 2020-03-09 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isicwebdatabase', '0008_auto_20200309_1517'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='interoperability',
            table='interoperability',
        ),
        migrations.AlterModelTable(
            name='isicapplicant',
            table='applicant_list',
        ),
    ]
