# Generated by Django 3.0 on 2020-03-09 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isicwebdatabase', '0009_auto_20200309_1522'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='interoperability',
            table='interoperability ',
        ),
    ]
