# Generated by Django 3.0 on 2020-03-09 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isicwebdatabase', '0010_auto_20200309_1524'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='isicapplicant',
            table='applicantlist',
        ),
    ]
