# Generated by Django 3.0 on 2020-03-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isicwebdatabase', '0011_auto_20200309_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('primary_key', models.BigIntegerField(primary_key=True, serialize=False)),
                ('site_name', models.CharField(default='Unknown', max_length=255)),
                ('site_alias', models.CharField(default='Unknown', max_length=255)),
                ('site_id', models.CharField(default=0, max_length=255)),
            ],
            options={
                'db_table': 'site',
                'managed': False,
            },
        ),
    ]
