# Generated by Django 3.0 on 2020-03-18 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isicwebdatabase', '0012_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenderPDF',
            fields=[
                ('primary_key', models.BigIntegerField(primary_key=True, serialize=False)),
                ('pdf_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isicwebdatabase.Site')),
            ],
        ),
    ]
