# Generated by Django 3.0 on 2020-03-18 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isicwebdatabase', '0013_renderpdf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RenderPDF',
        ),
    ]
