# Generated by Django 3.0 on 2020-03-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isicwebdatabase', '0014_delete_renderpdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenderPDF',
            fields=[
                ('primary_key', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'pdf',
                'managed': False,
            },
        ),
    ]
