# Generated by Django 3.0 on 2020-08-14 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isicwebdatabase', '0015_renderpdf'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='isicapplicant',
            table='applicant',
        ),
    ]
