# Generated by Django 3.0 on 2020-08-14 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isicwebdatabase', '0016_auto_20200814_0948'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='isicapplicant',
            table='applicants',
        ),
    ]
